# Generated by Django 6.0.6 on 2026-07-02 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentControleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supprime_le', models.DateTimeField(blank=True, editable=False, null=True)),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('poste', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_controleur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent contrôleur',
                'verbose_name_plural': 'Agents contrôleurs',
            },
        ),
    ]
