# Generated by Django 6.0.6 on 2026-07-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_categorieprofessionnelle_statutagent_typecontrat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(choices=[('anniversaire', 'Anniversaire'), ('anniversaire_service', 'Anniversaire de service'), ('fin_contrat', 'Fin de contrat'), ('conge', 'Congé à venir'), ('avancement', 'Avancement à examiner')], max_length=30)),
                ('objet', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('date_echeance', models.DateField(db_index=True)),
                ('niveau', models.CharField(choices=[('info', 'Info'), ('important', 'Important'), ('urgent', 'Urgent')], default='info', max_length=10)),
                ('traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Rappel',
                'ordering': ['traite', 'date_echeance'],
                'constraints': [models.UniqueConstraint(fields=('type_rappel', 'employe', 'date_echeance'), name='unique_rappel_type_employe_echeance')],
            },
        ),
    ]
