# Generated by Django 6.0.6 on 2026-06-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_date_naissance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('type_acte', models.CharField(choices=[('presence', 'Présence au poste'), ('mise_a_pied', 'Mise à pied'), ('demande_explication', "Demande d'explication"), ('avertissement', 'Avertissement'), ('felicitation', 'Lettre de félicitations'), ('note_service', 'Note de service'), ('attestation', 'Attestation'), ('autre', 'Autre')], max_length=30)),
                ('objet', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('date_acte', models.DateField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emis', 'Émis'), ('signe', 'Signé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('fichier', models.FileField(blank=True, upload_to='actes/')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes', to='employees.employee')),
                ('redige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_rediges', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Acte administratif',
                'verbose_name_plural': 'Actes administratifs',
                'ordering': ['-date_acte', '-id'],
            },
        ),
    ]
