# Generated by Django 6.0.6 on 2026-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes', '0002_alter_acteadministratif_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteadministratif',
            name='reference',
            field=models.CharField(blank=True, help_text='Généré automatiquement si laissé vide.', max_length=50),
        ),
    ]
