# Generated by Django 6.0.6 on 2026-07-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_categorieprofessionnelle_statutagent_typecontrat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('taux_salarial', models.DecimalField(decimal_places=2, help_text='% part salariale', max_digits=5)),
                ('taux_patronal', models.DecimalField(decimal_places=2, default=0, help_text='% part patronale', max_digits=5)),
            ],
            options={
                'verbose_name': 'Taux de cotisation',
                'verbose_name_plural': 'Taux de cotisation',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AllocationConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('libelle', models.CharField(blank=True, max_length=150)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_conge', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Allocation de congé',
                'verbose_name_plural': 'Allocations de congé',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('rembourse', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Avance sur salaire',
                'verbose_name_plural': 'Avances sur salaire',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('libelle', models.CharField(max_length=150)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('imposable', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Prime',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('montant_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_effet', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Salaire',
                'ordering': ['-date_effet'],
            },
        ),
    ]
