# Generated by Django 6.0.6 on 2026-07-03 00:20

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='scan_signe',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), core.validators.ValidateurTailleFichier(10)]),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='scan_signe',
            field=models.FileField(blank=True, null=True, upload_to='scans_signes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), core.validators.ValidateurTailleFichier(10)]),
        ),
        migrations.AlterField(
            model_name='historicalreponsepage2',
            name='contrat_sous_traitance_fichier',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), core.validators.ValidateurTailleFichier(10)]),
        ),
        migrations.AlterField(
            model_name='reponsepage2',
            name='contrat_sous_traitance_fichier',
            field=models.FileField(blank=True, null=True, upload_to='contrats_sous_traitance/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), core.validators.ValidateurTailleFichier(10)]),
        ),
    ]
