# Generated by Django 6.0.6 on 2026-07-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_historicalmissioncontrole_scan_signe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reponsetraitement',
            options={'ordering': ['traitement'], 'verbose_name': 'Réponse traitement', 'verbose_name_plural': 'Réponses traitement'},
        ),
    ]
