# Generated by Django 6.0.6 on 2026-07-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_historicalmissioncontrole_scan_signe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='date_signature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='deliberation_numero',
            field=models.CharField(blank=True, help_text='Délibération portant adoption de la procédure des missions de contrôle.', max_length=50, verbose_name='N° de délibération'),
        ),
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='deliberation_organe',
            field=models.CharField(blank=True, default="Conseil de l'APDPVP", max_length=255, verbose_name='Organe de la délibération'),
        ),
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='heure_controle',
            field=models.CharField(blank=True, help_text='Ex. 09h30', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='heure_signature',
            field=models.CharField(blank=True, help_text='Ex. 12h15', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='lieu_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='mode_pv',
            field=models.CharField(blank=True, choices=[('in situ', 'In situ'), ('en ligne', 'En ligne')], max_length=10),
        ),
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='nom_representant_entite',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom du représentant de l'entité"),
        ),
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='pv_document',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Procès-verbal (document généré)'),
        ),
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='pv_document_pdf',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Procès-verbal (PDF généré)'),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='date_signature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='deliberation_numero',
            field=models.CharField(blank=True, help_text='Délibération portant adoption de la procédure des missions de contrôle.', max_length=50, verbose_name='N° de délibération'),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='deliberation_organe',
            field=models.CharField(blank=True, default="Conseil de l'APDPVP", max_length=255, verbose_name='Organe de la délibération'),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='heure_controle',
            field=models.CharField(blank=True, help_text='Ex. 09h30', max_length=20),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='heure_signature',
            field=models.CharField(blank=True, help_text='Ex. 12h15', max_length=20),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='lieu_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='mode_pv',
            field=models.CharField(blank=True, choices=[('in situ', 'In situ'), ('en ligne', 'En ligne')], max_length=10),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='nom_representant_entite',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom du représentant de l'entité"),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='pv_document',
            field=models.FileField(blank=True, null=True, upload_to='pv/%Y/%m/', verbose_name='Procès-verbal (document généré)'),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='pv_document_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pv/%Y/%m/', verbose_name='Procès-verbal (PDF généré)'),
        ),
        migrations.AddField(
            model_name='reponsetraitement',
            name='evaluation',
            field=models.CharField(blank=True, choices=[('cto', 'Conformité totale'), ('cpa', 'Conformité partielle'), ('nc', 'Non conforme'), ('cpr', 'Constatation préoccupante')], max_length=3),
        ),
        migrations.AddField(
            model_name='reponsetraitement',
            name='observations_controleur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reponsetraitement',
            name='observations_entite',
            field=models.TextField(blank=True),
        ),
    ]
