# Generated by Django 6.0.6 on 2026-07-04 14:12

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_historicalmissioncontrole_date_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='rapport_signe',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), core.validators.ValidateurTailleFichier(10)], verbose_name='Rapport signé (scan)'),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='rapport_signe',
            field=models.FileField(blank=True, null=True, upload_to='rapports_signes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), core.validators.ValidateurTailleFichier(10)], verbose_name='Rapport signé (scan)'),
        ),
        migrations.AlterField(
            model_name='historicalmissioncontrole',
            name='statut',
            field=models.IntegerField(choices=[(10, 'Brouillon'), (20, 'Planifiée'), (30, 'En cours'), (40, 'Questionnaire complété'), (50, 'Procès-verbal généré'), (60, 'Procès-verbal signé uploadé'), (70, 'Rapport généré'), (80, 'Rapport signé uploadé'), (90, 'Validée')], default=10),
        ),
        migrations.AlterField(
            model_name='journalaction',
            name='type_action',
            field=models.CharField(choices=[('creation', 'Création de la mission'), ('questionnaire_complete', 'Questionnaire complété'), ('pv_genere', 'Procès-verbal généré'), ('scan_upload', 'Procès-verbal signé uploadé'), ('rapport_genere', 'Rapport généré'), ('rapport_scan_upload', 'Rapport signé uploadé'), ('validation', 'Mission validée')], max_length=30),
        ),
        migrations.AlterField(
            model_name='missioncontrole',
            name='statut',
            field=models.IntegerField(choices=[(10, 'Brouillon'), (20, 'Planifiée'), (30, 'En cours'), (40, 'Questionnaire complété'), (50, 'Procès-verbal généré'), (60, 'Procès-verbal signé uploadé'), (70, 'Rapport généré'), (80, 'Rapport signé uploadé'), (90, 'Validée')], default=10),
        ),
    ]
