# Generated by Django 5.2.6 on 2026-09-06 12:38

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_historicalmissioncontrole_rapport_signe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmissioncontrole',
            name='ordre_mission',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), core.validators.ValidateurTailleFichier(10)], verbose_name='Ordre de mission'),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='ordre_mission',
            field=models.FileField(blank=True, null=True, upload_to='ordres_mission/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), core.validators.ValidateurTailleFichier(10)], verbose_name='Ordre de mission'),
        ),
    ]
