# Generated by Django 5.2.6 on 2026-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entites', '0002_entitecontrolee_secteur_activite'),
        ('missions', '0007_historicalmissioncontrole_ordre_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioncontrole',
            name='entites_controlees',
            field=models.ManyToManyField(blank=True, related_name='missions_multi', to='entites.entitecontrolee'),
        ),
    ]
