# Generated by Django 5.2.6 on 2026-09-06 12:53

from django.db import migrations


def copier_entite_vers_m2m(apps, schema_editor):
    MissionControle = apps.get_model("missions", "MissionControle")
    for mission in MissionControle.objects.all():
        if mission.entite_controlee_id:
            mission.entites_controlees.add(mission.entite_controlee_id)


def copier_m2m_vers_entite(apps, schema_editor):
    MissionControle = apps.get_model("missions", "MissionControle")
    for mission in MissionControle.objects.all():
        premiere_entite = mission.entites_controlees.order_by("pk").first()
        if premiere_entite:
            mission.entite_controlee_id = premiere_entite.pk
            mission.save(update_fields=["entite_controlee"])


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_missioncontrole_entites_controlees'),
    ]

    operations = [
        migrations.RunPython(copier_entite_vers_m2m, copier_m2m_vers_entite),
    ]
