# Generated by Django 5.2.6 on 2026-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entites', '0002_entitecontrolee_secteur_activite'),
        ('missions', '0009_migrer_entite_controlee_vers_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmissioncontrole',
            name='entite_controlee',
        ),
        migrations.RemoveField(
            model_name='missioncontrole',
            name='entite_controlee',
        ),
        migrations.AlterField(
            model_name='missioncontrole',
            name='entites_controlees',
            field=models.ManyToManyField(related_name='missions', to='entites.entitecontrolee'),
        ),
    ]
