# Generated by Django 6.0.6 on 2026-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('prestataire', models.CharField(max_length=200)),
                ('type_formation', models.CharField(choices=[('technique', 'Technique'), ('soft_skills', 'Soft-skills'), ('management', 'Management')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_heures', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='planifie', max_length=20)),
                ('participants', models.ManyToManyField(blank=True, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['-date_debut'],
            },
        ),
    ]
