# Generated by Django 6.0.6 on 2026-07-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_categorieprofessionnelle_statutagent_typecontrat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_effet', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('motif', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, upload_to='avancements/')),
                ('ancienne_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.categorieprofessionnelle')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancements', to='employees.employee')),
                ('nouvelle_categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avancements', to='employees.categorieprofessionnelle')),
            ],
            options={
                'verbose_name': 'Avancement',
                'ordering': ['-date_effet'],
            },
        ),
    ]
