# Generated by Django 6.0.6 on 2026-06-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=100)),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('pourvu', 'Pourvu')], default='ouvert', max_length=10)),
                ('description', models.TextField()),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date_candidature', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('examen', 'En examen'), ('entretien', 'Entretien'), ('offre', 'Offre'), ('refuse', 'Refusé')], default='examen', max_length=20)),
                ('note', models.PositiveSmallIntegerField(default=0)),
                ('cv', models.FileField(blank=True, upload_to='cvs/')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='recruitment.jobposting')),
            ],
            options={
                'verbose_name': 'Candidat',
                'ordering': ['-date_candidature'],
            },
        ),
    ]
