# Generated by Django 6.0.6 on 2026-07-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_candidate_created_at_candidate_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='lettre_motivation',
            field=models.FileField(blank=True, upload_to='candidatures/lettres/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='priorite',
            field=models.CharField(choices=[('normale', 'Normale'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normale', max_length=12),
        ),
        migrations.AddField(
            model_name='candidate',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='type_demande',
            field=models.CharField(choices=[('emploi', "Demande d'emploi"), ('stage', 'Demande de stage')], default='emploi', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='recruitment.jobposting'),
        ),
    ]
