# Generated by Django 6.0.6 on 2026-06-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_created_at_department_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
