# Generated by Django 6.0.6 on 2026-06-28 18:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_user_alter_employee_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('niveau', models.PositiveSmallIntegerField(default=1, help_text="Pour l'ordre d'avancement")),
            ],
            options={
                'verbose_name': 'Catégorie professionnelle',
                'verbose_name_plural': 'Catégories professionnelles',
                'ordering': ['-niveau', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='StatutAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "Statut d'agent",
                'verbose_name_plural': "Statuts d'agent",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Type de contrat',
                'verbose_name_plural': 'Types de contrat',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='employee',
            name='lettre_motivation',
            field=models.FileField(blank=True, upload_to='lettres/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='employee',
            name='matricule_apdpvp',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matricule APDPVP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='matricule_cnamgs',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matricule CNAMGS'),
        ),
        migrations.AddField(
            model_name='employee',
            name='matricule_cnss',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matricule CNSS'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nombre_enfants',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='statut_matrimonial',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf(ve)'), ('union_libre', 'Union libre')], default='celibataire', max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone 2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone_urgence',
            field=models.CharField(blank=True, max_length=30, verbose_name="Téléphone d'urgence"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_embauche',
            field=models.DateField(help_text='Ne change pas après création.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.CharField(blank=True, help_text='Poste principal (libellé). Voir aussi Affectations.', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.categorieprofessionnelle'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Vide = en cours / indéterminé', null=True)),
                ('fichier', models.FileField(blank=True, upload_to='contrats/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Contrat',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('intitule', models.CharField(max_length=200)),
                ('etablissement', models.CharField(blank=True, max_length=200)),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, upload_to='diplomes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Diplôme',
                'ordering': ['-annee', 'intitule'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_evaluation', models.DateField()),
                ('note', models.PositiveSmallIntegerField(default=0, help_text='Sur 20')),
                ('appreciation', models.TextField(blank=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='employees.employee')),
                ('evaluateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_menees', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('intitule', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Sert à générer la fiche de poste')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
            ],
            options={
                'verbose_name': 'Poste',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='employees.employee')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='employees.poste')),
            ],
            options={
                'verbose_name': 'Affectation',
                'ordering': ['-principal', '-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='statut_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.statutagent'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('matricule_cnss', ''), _negated=True)), fields=('matricule_cnss',), name='unique_cnss_actif'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('matricule_cnamgs', ''), _negated=True)), fields=('matricule_cnamgs',), name='unique_cnamgs_actif'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('matricule_apdpvp', ''), _negated=True)), fields=('matricule_apdpvp',), name='unique_apdpvp_actif'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.typecontrat'),
        ),
    ]
