# Generated by Django 6.0.6 on 2026-06-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('contrat', 'Contrat'), ('politique', 'Politique'), ('formation', 'Formation'), ('evaluation', 'Évaluation'), ('autre', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('acces_employes', models.ManyToManyField(blank=True, related_name='documents_accessibles', to='employees.employee')),
                ('uploade_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['-date_upload'],
            },
        ),
    ]
