# Generated by Django 6.0.6 on 2026-07-02 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supprime_le', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=255)),
                ('service', models.CharField(blank=True, max_length=255)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='entites.entitecontrolee')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='personnes.personne')),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'unique_together': {('personne', 'entite', 'poste', 'date_debut')},
            },
        ),
    ]
