# Generated by Django 6.0.6 on 2026-07-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntiteControlee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supprime_le', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Entité contrôlée',
                'verbose_name_plural': 'Entités contrôlées',
            },
        ),
    ]
