# Generated by Django 5.2.6 on 2026-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitecontrolee',
            name='secteur_activite',
            field=models.CharField(blank=True, choices=[('administration', 'Administration publique'), ('banque_finance', 'Banque / Finance / Assurance'), ('commerce', 'Commerce'), ('education', 'Éducation'), ('hotellerie_restauration', 'Hôtellerie / Restauration'), ('immobilier', 'Immobilier'), ('industrie', 'Industrie'), ('informatique_telecom', 'Informatique / Télécommunications'), ('ong_association', 'ONG / Association'), ('sante', 'Santé'), ('transport_logistique', 'Transport / Logistique'), ('autre', 'Autre')], max_length=30, verbose_name="Secteur d'activité"),
        ),
    ]
